# Supabase Configuration for Vaccine Tracker MVP
# This file is used if running Supabase locally via CLI

project_id = "bsdpgfththdkuwihoomdk"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

# Simple email/password auth for MVP
# No email templates needed (confirmations disabled)
