# Defines lint rules for Dart code
# More info: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print: false  # Allow print statements for debugging in MVP
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_unnecessary_containers

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
